name: Labels

on:
  pull_request:
    # types: [created, labeled]
  issues:
    types: [opened, labeled]

jobs:
  to_project:
    name: move PR / issue with project label to project
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: ${{ contains(github.event.pull_request.labels.*.name, 'project') || contains(github.event.issue.labels.*.name, 'project') }}
        with:
          project: Project
          column: To Do
          repo-token: ${{ secrets.TEST_SECRET }}
  to_slack:
      name: Notificate via Slack when specific labels are attached
      runs-on: ubuntu-latest
      steps:
        - uses: 8398a7/action-slack@v3
          if: ${{ contains(github.event.pull_request.labels.*.name, 'project') }}
          with:
            status: custom
            fields: workflow,job,commit,repo,ref,author,took
            custom_payload: |
              {
                username: 'action-slack',
                icon_emoji: ':octocat:',
                attachments: [{
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: `${process.env.GITHUB_REPOSITORY} \n
                  ${process.env.GITHUB_REF} \n
                  ${env.PR}`
                }]
              }

            # fields: repo,message,author,workflow # selectable (default: repo,message)
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
            PR: github.event.pull_request
